### ISSUE TITLE
Error running live: channel 0

### ISSUE THREAD

**Issue by millette** [watson/npm-dependency-db#8]
Using 6.0.5.

```
$ npm-dependency-db  --update  --live
cache location: /home/millette/.npm-dependency-db
downloaded 34011 [0.2 pkg/s, 214 B/s]
processed  34011 [0.2 pkg/s]
/home/millette/n/lib/node_modules/npm-dependency-db/node_modules/hypercore/lib/protocol.js:219
  if (channel !== 0) throw new Error('Only channel 0 is supported')
                     ^

Error: Only channel 0 is supported
    at Protocol._onmessage (/home/millette/n/lib/node_modules/npm-dependency-db/node_modules/hypercore/lib/protocol.js:219:28)
    at Protocol._parse (/home/millette/n/lib/node_modules/npm-dependency-db/node_modules/hypercore/lib/protocol.js:273:14)
    at Protocol._descryptAndParse (/home/millette/n/lib/node_modules/npm-dependency-db/node_modules/hypercore/lib/protocol.js:202:8)
    at Protocol._write (/home/millette/n/lib/node_modules/npm-dependency-db/node_modules/hypercore/lib/protocol.js:197:8)
    at Protocol._parse (/home/millette/n/lib/node_modules/npm-dependency-db/node_modules/hypercore/lib/protocol.js:279:14)
    at Protocol._descryptAndParse (/home/millette/n/lib/node_modules/npm-dependency-db/node_modules/hypercore/lib/protocol.js:202:8)
    at Protocol._write (/home/millette/n/lib/node_modules/npm-dependency-db/node_modules/hypercore/lib/protocol.js:197:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at Protocol.Writable.write (_stream_writable.js:247:11)
```

I'll update the package and try again.

**Comment by mafintosh** [comment]
Reinstall and this should be fixed

**Comment by millette** [comment]
It had been running for a few days. Only saw this error once (I wouldn't know how to replicate it).

I upgraded since I notice a new versions (6.0.7), will comment here if I see that error again. Going to close for now.

**Comment by watson** [comment]
@millette thank you 😃 I really appreciate your help and feedback 🙏
